title:
    fr: 'Alex Press'
    en: 'Alex Press'

config:
    langs: 
        - en
        - fr
    defaultLang: 'en'
    defaultPage: 'home'
    meta:
        description: 
            en: 'A dedicated theme like VuePress but working with Alex'
            fr: 'Un thème dédié comme VuePress qui fonctionne avec Alex'
        keywords: 
            - press 
            - documentation 
            - alex
            - website generator
    scripts:
        #-
        #    source: 'https://xxxx.com/script.js'

theme:
    icon: /assets/user/imgs/falcon.svg
    start: 'guide'

menu:
    - 
        content: home
        name: 
            fr: 'Accueil'
            en: 'Home'
        external: false
        hide: false
    -
        content: guide
        name: 
            fr: 'Documentation'
            en: 'Guide'
        external: false
        hide: false
        submenus: 
            -
                content: overview
                name:
                    fr: 'Vue générale'
                    en: 'Overview'
                external: false
                hide: false
            -
                content: configuration 
                name:
                    fr: 'Configuration'
                    en: 'Settings'
                external: false
                hide: false
                submenus: 
                    -
                        content: global 
                        name:
                            fr: 'Généralités'
                            en: 'General'
                            hide: false
                            external: false
                    -
                        content: math 
                        name:
                            fr: 'Support des maths'
                            en: 'Math support'
                            hide: false
                            external: false
                    -
                        content: langs 
                        name:
                            fr: 'Support multilingues'
                            en: 'Multilingual support'
                            hide: false
                            external: false
    -
        content: code
        name:
            fr: 'Code'
            en: 'Code'
        icon: 'fab fa-github'
        external: true
        link: 'http://github.com/etermind/alex'
        target: '_blank'
